name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} .

      - name: Tag Docker Image
        run: |
          docker tag \
            ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Get Image Digest
        id: image-digest
        run: |
          DIGEST=$(aws ecr describe-images \
            --repository-name ${{ vars.ECR_REPOSITORY }} \
            --image-ids imageTag=${{ github.sha }} \
            --query 'imageDetails[0].imageDigest' \
            --output text)

          echo "digest=$DIGEST" >> $GITHUB_OUTPUT      

      - name: Sign Docker Image
        env:
            COSIGN_EXPERIMENTAL: "true"
        run: |
            cosign sign --yes \
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}@${{ steps.image-digest.outputs.digest }}   
            
      - name: Verify Docker Image Signature
        run: |
          cosign verify \
          --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/ci.yml@refs/heads/main" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}@${{ steps.image-digest.outputs.digest }}     